<?php
// The purpose of this module is to Add a link to every article node that updates a date field to today using ajax
/**
 * Implementation of hook_menu()
 */
function article_menu() {
		$items['update/date/ajax/%'] = array(
			'title' => t(''), 
			'description' => 'Update date functionality.',
			'page callback' => 'article_update_date',
			'type' => MENU_CALLBACK,
			'access callback' => TRUE,
			'page arguments' => array(2,3),
		);				
		return $items;
	}	
function article_node_view($node, $view_mode){ 
    switch ($node->type) {
		case 'article':
			drupal_add_library('system', 'drupal.ajax');
			$node->content['article_date']['#weight']=10;
		    $node->content['extra_link'] = array(
			  '#weight' => 11,
			  '#theme' => 'link',
			  '#path' => 'update/date/ajax/'.$node->nid,
			  '#text' => t('Mark as Complete'),
			  '#options' => array(
				  'attributes' => array('class' => 'use-ajax'),
				  'html' => FALSE
			  ),
		  );
      break;
	  	  
  }
}
/* function for update date */
function article_update_date($type = 'ajax',$nid){
	if ($type == 'ajax') { 
		$now = time();
		$query = db_update('field_data_article_date')
			  ->fields(array(
				'article_date_value' => $now,
			  ))
			  ->condition('entity_id', $nid, '=')
			  ->execute();
			  
		$commands[] = ajax_command_replace('.date-display-single', date('l, F j, Y - G:i',$now)); 
		$page = array('#type' => 'ajax', '#commands' => $commands); 
		ajax_deliver($page); 
	} 
	$cid = "field:node:".$nid;
	cache_clear_all($cid, 'cache_field', TRUE);
}

