# Schema for the configuration files of the Thank You Commenter module.

thank_you_commenter.settings:
  type: mapping
  label: 'Thank you commenter settings'
  mapping:
    message:
      type: text
      label: 'Message'   
