<?php

/**
 * @file
 * Allows support of a new view handler.
 */

/**
 * Implements hook_theme().
 */
function pgwslider_theme() {
  return array(
    'images_pgwslider_formatter' => array(
      'render element' => 'element',
      'file' => 'pgwslider.theme.inc',
    ),
    'image_pgwslider_formatter' => array(
      'variables' => array(
        'item' => NULL,
        'item_attributes' => NULL,
        'url' => NULL,
        'image_style' => NULL,
        'caption' => FALSE
      ),
      'file' => 'pgwslider.theme.inc',
    ),
  );
}